create sequence flight_seq start with 1 increment by 50;
create sequence operator_seq start with 1 increment by 50;
create table flight (date_of_departure date not null, id integer not null, number_seats_available integer not null, number_seats_total integer not null, operator_id integer, time_of_departure time(6) not null, destination varchar(255) not null, leaving varchar(255) not null, primary key (id));
create table operator (id integer not null, api_search varchar(255) not null unique, iban varchar(255) not null unique, name varchar(255) not null unique, primary key (id));
alter table if exists flight add constraint FK2tqfrlqvqkatj9e5hkd7m2ymn foreign key (operator_id) references operator;
create sequence flight_seq start with 1 increment by 50;
create sequence operator_seq start with 1 increment by 50;
create table flight (date_of_departure date not null, id integer not null, number_seats_available integer not null, number_seats_total integer not null, operator_id integer, time_of_departure time(6) not null, destination varchar(255) not null, leaving varchar(255) not null, primary key (id));
create table operator (id integer not null, api_search varchar(255) not null unique, iban varchar(255) not null unique, name varchar(255) not null unique, primary key (id));
alter table if exists flight add constraint FK2tqfrlqvqkatj9e5hkd7m2ymn foreign key (operator_id) references operator;
create sequence flight_seq start with 1 increment by 50;
create sequence operator_seq start with 1 increment by 50;
create table flight (date_of_departure date not null, id integer not null, number_seats_available integer not null, number_seats_total integer not null, operator_id integer, time_of_departure time(6) not null, destination varchar(255) not null, leaving varchar(255) not null, primary key (id));
create table operator (id integer not null, api_search varchar(255) not null unique, iban varchar(255) not null unique, name varchar(255) not null unique, primary key (id));
alter table if exists flight add constraint FK2tqfrlqvqkatj9e5hkd7m2ymn foreign key (operator_id) references operator;
create sequence flight_seq start with 1 increment by 50;
create sequence operator_seq start with 1 increment by 50;
create table flight (date_of_departure date not null, id integer not null, number_seats_available integer not null, number_seats_total integer not null, operator_id integer, time_of_departure time(6) not null, destination varchar(255) not null, leaving varchar(255) not null, primary key (id));
create table operator (id integer not null, api_search varchar(255) not null unique, iban varchar(255) not null unique, name varchar(255) not null unique, primary key (id));
alter table if exists flight add constraint FK2tqfrlqvqkatj9e5hkd7m2ymn foreign key (operator_id) references operator;
create sequence flight_seq start with 1 increment by 50;
create sequence operator_seq start with 1 increment by 50;
create table flight (date_of_departure date not null, id integer not null, number_seats_available integer not null, number_seats_total integer not null, operator_id integer, time_of_departure time(6) not null, destination varchar(255) not null, leaving varchar(255) not null, primary key (id));
create table operator (id integer not null, api_search varchar(255) not null unique, iban varchar(255) not null unique, name varchar(255) not null unique, primary key (id));
alter table if exists flight add constraint FK2tqfrlqvqkatj9e5hkd7m2ymn foreign key (operator_id) references operator;
create sequence flight_seq start with 1 increment by 50;
create sequence operator_seq start with 1 increment by 50;
create table flight (date_of_departure date not null, id integer not null, number_seats_available integer not null, number_seats_total integer not null, operator_id integer, time_of_departure time(6) not null, destination varchar(255) not null, leaving varchar(255) not null, primary key (id));
create table operator (id integer not null, api_search varchar(255) not null unique, iban varchar(255) not null unique, name varchar(255) not null unique, primary key (id));
alter table if exists flight add constraint FK2tqfrlqvqkatj9e5hkd7m2ymn foreign key (operator_id) references operator;
create sequence flight_seq start with 1 increment by 50;
create sequence operator_seq start with 1 increment by 50;
create table flight (date_of_departure date not null, id integer not null, number_seats_available integer not null, number_seats_total integer not null, operator_id integer, time_of_departure time(6) not null, destination varchar(255) not null, leaving varchar(255) not null, primary key (id));
create table operator (id integer not null, api_search varchar(255) not null unique, iban varchar(255) not null unique, name varchar(255) not null unique, primary key (id));
alter table if exists flight add constraint FK2tqfrlqvqkatj9e5hkd7m2ymn foreign key (operator_id) references operator;
create sequence flight_seq start with 1 increment by 50;
create sequence operator_seq start with 1 increment by 50;
create table flight (date_of_departure date not null, id integer not null, number_seats_available integer not null, number_seats_total integer not null, operator_id integer, time_of_departure time(6) not null, destination varchar(255) not null, leaving varchar(255) not null, primary key (id));
create table operator (id integer not null, api_search varchar(255) not null unique, iban varchar(255) not null unique, name varchar(255) not null unique, primary key (id));
alter table if exists flight add constraint FK2tqfrlqvqkatj9e5hkd7m2ymn foreign key (operator_id) references operator;
create sequence flight_seq start with 1 increment by 50;
create sequence operator_seq start with 1 increment by 50;
create table flight (date_of_departure date not null, id integer not null, number_seats_available integer not null, number_seats_total integer not null, operator_id integer, time_of_departure time(6) not null, destination varchar(255) not null, leaving varchar(255) not null, primary key (id));
create table operator (id integer not null, api_search varchar(255) not null unique, iban varchar(255) not null unique, name varchar(255) not null unique, primary key (id));
alter table if exists flight add constraint FK2tqfrlqvqkatj9e5hkd7m2ymn foreign key (operator_id) references operator;
create sequence flight_seq start with 1 increment by 50;
create sequence operator_seq start with 1 increment by 50;
create table flight (date_of_departure date not null, id integer not null, number_seats_available integer not null, number_seats_total integer not null, operator_id integer, time_of_departure time(6) not null, destination varchar(255) not null, leaving varchar(255) not null, primary key (id));
create table operator (id integer not null, api_search varchar(255) not null unique, iban varchar(255) not null unique, name varchar(255) not null unique, primary key (id));
alter table if exists flight add constraint FK2tqfrlqvqkatj9e5hkd7m2ymn foreign key (operator_id) references operator;
create sequence flight_seq start with 1 increment by 50;
create sequence operator_seq start with 1 increment by 50;
create table flight (date_of_departure date not null, id integer not null, number_seats_available integer not null, number_seats_total integer not null, operator_id integer, time_of_departure time(6) not null, destination varchar(255) not null, leaving varchar(255) not null, primary key (id));
create table operator (id integer not null, api_search varchar(255) not null unique, iban varchar(255) not null unique, name varchar(255) not null unique, primary key (id));
alter table if exists flight add constraint FK2tqfrlqvqkatj9e5hkd7m2ymn foreign key (operator_id) references operator;
create sequence flight_seq start with 1 increment by 50;
create sequence operator_seq start with 1 increment by 50;
create table flight (date_of_departure date not null, id integer not null, number_seats_available integer not null, number_seats_total integer not null, operator_id integer, time_of_departure time(6) not null, destination varchar(255) not null, leaving varchar(255) not null, primary key (id));
create table operator (id integer not null, api_search varchar(255) not null unique, iban varchar(255) not null unique, name varchar(255) not null unique, primary key (id));
alter table if exists flight add constraint FK2tqfrlqvqkatj9e5hkd7m2ymn foreign key (operator_id) references operator;
create sequence flight_seq start with 1 increment by 50;
create sequence operator_seq start with 1 increment by 50;
create table flight (date_of_departure date not null, id integer not null, number_seats_available integer not null, number_seats_total integer not null, operator_id integer, time_of_departure time(6) not null, destination varchar(255) not null, leaving varchar(255) not null, primary key (id));
create table operator (id integer not null, api_search varchar(255) not null unique, iban varchar(255) not null unique, name varchar(255) not null unique, primary key (id));
alter table if exists flight add constraint FK2tqfrlqvqkatj9e5hkd7m2ymn foreign key (operator_id) references operator;
create sequence flight_seq start with 1 increment by 50;
create sequence operator_seq start with 1 increment by 50;
create table flight (date_of_departure date not null, id integer not null, number_seats_available integer not null, number_seats_total integer not null, operator_id integer, time_of_departure time(6) not null, destination varchar(255) not null, leaving varchar(255) not null, primary key (id));
create table operator (id integer not null, api_search varchar(255) not null unique, iban varchar(255) not null unique, name varchar(255) not null unique, primary key (id));
alter table if exists flight add constraint FK2tqfrlqvqkatj9e5hkd7m2ymn foreign key (operator_id) references operator;
create sequence flight_seq start with 1 increment by 50;
create sequence operator_seq start with 1 increment by 50;
create table flight (date_of_departure date not null, id integer not null, number_seats_available integer not null, number_seats_total integer not null, operator_id integer, time_of_departure time(6) not null, destination varchar(255) not null, leaving varchar(255) not null, primary key (id));
create table operator (id integer not null, api_search varchar(255) not null unique, iban varchar(255) not null unique, name varchar(255) not null unique, primary key (id));
alter table if exists flight add constraint FK2tqfrlqvqkatj9e5hkd7m2ymn foreign key (operator_id) references operator;
create sequence flight_seq start with 1 increment by 50;
create sequence operator_seq start with 1 increment by 50;
create table flight (date_of_departure date not null, id integer not null, number_seats_available integer not null, number_seats_total integer not null, operator_id integer, time_of_departure time(6) not null, destination varchar(255) not null, leaving varchar(255) not null, primary key (id));
create table operator (id integer not null, api_search varchar(255) not null unique, iban varchar(255) not null unique, name varchar(255) not null unique, primary key (id));
alter table if exists flight add constraint FK2tqfrlqvqkatj9e5hkd7m2ymn foreign key (operator_id) references operator;
create sequence flight_seq start with 1 increment by 50;
create sequence operator_seq start with 1 increment by 50;
create table flight (date_of_departure date not null, id integer not null, number_seats_available integer not null, number_seats_total integer not null, operator_id integer, time_of_departure time(6) not null, destination varchar(255) not null, leaving varchar(255) not null, primary key (id));
create table operator (id integer not null, api_search varchar(255) not null unique, iban varchar(255) not null unique, name varchar(255) not null unique, primary key (id));
alter table if exists flight add constraint FK2tqfrlqvqkatj9e5hkd7m2ymn foreign key (operator_id) references operator;
create sequence flight_seq start with 1 increment by 50;
create sequence operator_seq start with 1 increment by 50;
create table flight (date_of_departure date not null, id integer not null, number_seats_available integer not null, number_seats_total integer not null, operator_id integer, time_of_departure time(6) not null, destination varchar(255) not null, leaving varchar(255) not null, primary key (id));
create table operator (id integer not null, api_search varchar(255) not null unique, iban varchar(255) not null unique, name varchar(255) not null unique, primary key (id));
alter table if exists flight add constraint FK2tqfrlqvqkatj9e5hkd7m2ymn foreign key (operator_id) references operator;
create sequence flight_seq start with 1 increment by 50;
create sequence operator_seq start with 1 increment by 50;
create table flight (date_of_departure date not null, id integer not null, number_seats_available integer not null, number_seats_total integer not null, operator_id integer, time_of_departure time(6) not null, destination varchar(255) not null, leaving varchar(255) not null, primary key (id));
create table operator (id integer not null, api_search varchar(255) not null unique, iban varchar(255) not null unique, name varchar(255) not null unique, primary key (id));
alter table if exists flight add constraint FK2tqfrlqvqkatj9e5hkd7m2ymn foreign key (operator_id) references operator;
create sequence flight_seq start with 1 increment by 50;
create sequence operator_seq start with 1 increment by 50;
create table flight (date_of_departure date not null, id integer not null, number_seats_available integer not null, number_seats_total integer not null, operator_id integer, time_of_departure time(6) not null, destination varchar(255) not null, leaving varchar(255) not null, primary key (id));
create table operator (id integer not null, api_search varchar(255) not null unique, iban varchar(255) not null unique, name varchar(255) not null unique, primary key (id));
alter table if exists flight add constraint FK2tqfrlqvqkatj9e5hkd7m2ymn foreign key (operator_id) references operator;
create sequence flight_seq start with 1 increment by 50;
create sequence operator_seq start with 1 increment by 50;
create table flight (date_of_departure date not null, id integer not null, number_seats_available integer not null, number_seats_total integer not null, operator_id integer, time_of_departure time(6) not null, destination varchar(255) not null, leaving varchar(255) not null, primary key (id));
create table operator (id integer not null, api_search varchar(255) not null unique, iban varchar(255) not null unique, name varchar(255) not null unique, primary key (id));
alter table if exists flight add constraint FK2tqfrlqvqkatj9e5hkd7m2ymn foreign key (operator_id) references operator;
create sequence flight_seq start with 1 increment by 50;
create sequence operator_seq start with 1 increment by 50;
create table flight (date_of_departure date not null, id integer not null, number_seats_available integer not null, number_seats_total integer not null, operator_id integer, time_of_departure time(6) not null, destination varchar(255) not null, leaving varchar(255) not null, primary key (id));
create table operator (id integer not null, api_search varchar(255) not null unique, iban varchar(255) not null unique, name varchar(255) not null unique, primary key (id));
alter table if exists flight add constraint FK2tqfrlqvqkatj9e5hkd7m2ymn foreign key (operator_id) references operator;
create sequence flight_seq start with 1 increment by 50;
create sequence operator_seq start with 1 increment by 50;
create table flight (date_of_departure date not null, id integer not null, number_seats_available integer not null, number_seats_total integer not null, operator_id integer, time_of_departure time(6) not null, destination varchar(255) not null, leaving varchar(255) not null, primary key (id));
create table operator (id integer not null, api_search varchar(255) not null unique, iban varchar(255) not null unique, name varchar(255) not null unique, primary key (id));
alter table if exists flight add constraint FK2tqfrlqvqkatj9e5hkd7m2ymn foreign key (operator_id) references operator;
create sequence flight_seq start with 1 increment by 50;
create sequence operator_seq start with 1 increment by 50;
create table flight (date_of_departure date not null, id integer not null, number_seats_available integer not null, number_seats_total integer not null, operator_id integer, time_of_departure time(6) not null, destination varchar(255) not null, leaving varchar(255) not null, primary key (id));
create table operator (id integer not null, api_search varchar(255) not null unique, iban varchar(255) not null unique, name varchar(255) not null unique, primary key (id));
alter table if exists flight add constraint FK2tqfrlqvqkatj9e5hkd7m2ymn foreign key (operator_id) references operator;
create sequence flight_seq start with 1 increment by 50;
create sequence operator_seq start with 1 increment by 50;
create table flight (date_of_departure date not null, id integer not null, number_seats_available integer not null, number_seats_total integer not null, operator_id integer, time_of_departure time(6) not null, destination varchar(255) not null, leaving varchar(255) not null, primary key (id));
create table operator (id integer not null, api_search varchar(255) not null unique, iban varchar(255) not null unique, name varchar(255) not null unique, primary key (id));
alter table if exists flight add constraint FK2tqfrlqvqkatj9e5hkd7m2ymn foreign key (operator_id) references operator;
create sequence flight_seq start with 1 increment by 50;
create sequence operator_seq start with 1 increment by 50;
create table flight (date_of_departure date not null, id integer not null, number_seats_available integer not null, number_seats_total integer not null, operator_id integer, time_of_departure time(6) not null, destination varchar(255) not null, leaving varchar(255) not null, primary key (id));
create table operator (id integer not null, api_search varchar(255) not null unique, iban varchar(255) not null unique, name varchar(255) not null unique, primary key (id));
alter table if exists flight add constraint FK2tqfrlqvqkatj9e5hkd7m2ymn foreign key (operator_id) references operator;
create sequence flight_seq start with 1 increment by 50;
create sequence operator_seq start with 1 increment by 50;
create table flight (date_of_departure date not null, id integer not null, number_seats_available integer not null, number_seats_total integer not null, operator_id integer, time_of_departure time(6) not null, destination varchar(255) not null, leaving varchar(255) not null, primary key (id));
create table operator (id integer not null, api_search varchar(255) not null unique, iban varchar(255) not null unique, name varchar(255) not null unique, primary key (id));
alter table if exists flight add constraint FK2tqfrlqvqkatj9e5hkd7m2ymn foreign key (operator_id) references operator;
create sequence flight_seq start with 1 increment by 50;
create sequence operator_seq start with 1 increment by 50;
create table flight (date_of_departure date not null, id integer not null, number_seats_available integer not null, number_seats_total integer not null, operator_id integer, time_of_departure time(6) not null, destination varchar(255) not null, leaving varchar(255) not null, primary key (id));
create table operator (id integer not null, api_search varchar(255) not null unique, iban varchar(255) not null unique, name varchar(255) not null unique, primary key (id));
alter table if exists flight add constraint FK2tqfrlqvqkatj9e5hkd7m2ymn foreign key (operator_id) references operator;
create sequence flight_seq start with 1 increment by 50;
create sequence operator_seq start with 1 increment by 50;
create table flight (date_of_departure date not null, id integer not null, number_seats_available integer not null, number_seats_total integer not null, operator_id integer, time_of_departure time(6) not null, destination varchar(255) not null, leaving varchar(255) not null, primary key (id));
create table operator (id integer not null, api_search varchar(255) not null unique, iban varchar(255) not null unique, name varchar(255) not null unique, primary key (id));
alter table if exists flight add constraint FK2tqfrlqvqkatj9e5hkd7m2ymn foreign key (operator_id) references operator;
create sequence flight_seq start with 1 increment by 50;
create sequence operator_seq start with 1 increment by 50;
create table flight (date_of_departure date not null, id integer not null, number_seats_available integer not null, number_seats_total integer not null, operator_id integer, time_of_departure time(6) not null, destination varchar(255) not null, leaving varchar(255) not null, primary key (id));
create table operator (id integer not null, api_search varchar(255) not null unique, iban varchar(255) not null unique, name varchar(255) not null unique, primary key (id));
alter table if exists flight add constraint FK2tqfrlqvqkatj9e5hkd7m2ymn foreign key (operator_id) references operator;
create sequence flight_seq start with 1 increment by 50;
create sequence operator_seq start with 1 increment by 50;
create table flight (date_of_departure date not null, id integer not null, number_seats_available integer not null, number_seats_total integer not null, operator_id integer, time_of_departure time(6) not null, destination varchar(255) not null, leaving varchar(255) not null, primary key (id));
create table operator (id integer not null, api_search varchar(255) not null unique, iban varchar(255) not null unique, name varchar(255) not null unique, primary key (id));
alter table if exists flight add constraint FK2tqfrlqvqkatj9e5hkd7m2ymn foreign key (operator_id) references operator;
create sequence flight_seq start with 1 increment by 50;
create sequence operator_seq start with 1 increment by 50;
create table flight (date_of_departure date not null, id integer not null, number_seats_available integer not null, number_seats_total integer not null, operator_id integer, time_of_departure time(6) not null, destination varchar(255) not null, leaving varchar(255) not null, primary key (id));
create table operator (id integer not null, api_search varchar(255) not null unique, iban varchar(255) not null unique, name varchar(255) not null unique, primary key (id));
alter table if exists flight add constraint FK2tqfrlqvqkatj9e5hkd7m2ymn foreign key (operator_id) references operator;
